// <auto-generated />
using System;
using MWSProducts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MWSProductApp.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MWSProductApp.Model.MWSLogin", b =>
                {
                    b.Property<string>("LoginId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.ToTable("tbl_UserLogin");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSRefreshToken", b =>
                {
                    b.Property<string>("RefreshTokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MWSLoginLoginId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("MWSLoginLoginId");

                    b.ToTable("tbl_UserRefreshToken");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSRoles", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MWSUserRolesUserRoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.HasIndex("MWSUserRolesUserRoleId");

                    b.ToTable("tbl_refRoles");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSSetPassword", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Captcha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Security_Question_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Security_Question_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Security_Question_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Security_Question_4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("tbl_UserSetPassWord");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSUserRegister", b =>
                {
                    b.Property<string>("UserRegisterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MWSSetPasswordUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MWSUserRolesUserRoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRegisterId");

                    b.HasIndex("MWSSetPasswordUserId");

                    b.HasIndex("MWSUserRolesUserRoleId");

                    b.ToTable("tbl_UserRegister");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSUserRoles", b =>
                {
                    b.Property<string>("UserRoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRoleId");

                    b.ToTable("tbl_UserRoles");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSRefreshToken", b =>
                {
                    b.HasOne("MWSProductApp.Model.MWSLogin", "MWSLogin")
                        .WithMany()
                        .HasForeignKey("MWSLoginLoginId");

                    b.Navigation("MWSLogin");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSRoles", b =>
                {
                    b.HasOne("MWSProductApp.Model.MWSUserRoles", null)
                        .WithMany("Roles")
                        .HasForeignKey("MWSUserRolesUserRoleId");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSUserRegister", b =>
                {
                    b.HasOne("MWSProductApp.Model.MWSSetPassword", "MWSSetPassword")
                        .WithMany()
                        .HasForeignKey("MWSSetPasswordUserId");

                    b.HasOne("MWSProductApp.Model.MWSUserRoles", null)
                        .WithMany("Users")
                        .HasForeignKey("MWSUserRolesUserRoleId");

                    b.Navigation("MWSSetPassword");
                });

            modelBuilder.Entity("MWSProductApp.Model.MWSUserRoles", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
